examples/default/README.md, examples/default/main.tf, main.tf, output.tf, variables.tf, versions.tf
Fixed a few issues with the variables that are passed through to the ECS Task Definition, and updated the variables and examples as a result.
Fixed a few ease-of-use issues:
- default name for the task role was hitting a 64 character limit
- added a depends_on for the ECS task to require the cluster and task definition be created
- added specific required providers so that when `aws.<alias>` is passed to the module it doesn't throw warnings
Tested by deploying in us-east-1 and us-west-2 and validated task execution.
N/A
=> Module fixes after testing with the `0.23` TF provider

README.md, examples/default/README.md, examples/default/main.tf, examples/global_only/README.md, examples/global_only/main.tf, output.tf, variables.tf
This is a change to the README to document more of the inputs.
The change also updates the example READMEs to correct the inputs (to include `lacework_account`).
Finally, this flips the default for `regional` from `true` to `false`. This feels safer as people have to opt-in to creating the regional resources.
Deployed this module.
N/A
=> fix: Update readme and examples with required inputs

README.md, main.tf, variables.tf
Signed-off-by: Teddy Reed <teddy.reed@lacework.net>
The S3 bucket is used for temporary state. It can be safely removed at anytime.
Run the module locally and remove (verify no error on removal).
N/A
=> Add force_destroy to S3 bucket

README.md, examples/global-only/README.md, examples/global-only/main.tf, variables.tf
This updates our README and examples to use the new `prefix` and `suffix` inputs.
There are various other cosmetic improvements.
=> Fix docs and examples for changed inputs

main.tf
This fix tells the module to ignore changes to the ECS cluster tags.
The sidekick scanner appears to add several tags to the ECS cluster(s) upon execution.  Since Terraform is unaware of those changes, it will try to remove them unless we tell it not to.  The module should be idempotent.
Tested in my organization with a running scanner.
N/A
=> fix: ignore out-of-band updates to ECS cluster tags

README.md, examples/default/README.md, examples/default/main.tf, main.tf, output.tf, variables.tf
The `suffix` input allows module users to add uniqueness to the resources created. This helps in the rare situations where multiple agentless integrations are installed into the same account and same region.
We should set this value as an output so that folks can use the same suffix in both global and regional deployments.
We also use the prefix as our unique identifier name namespace (then the resource name) for restricting access in IAM conditions. 
Output suffix and update example to set the same suffix name in both modules.
=> fix: Output the suffix and prefix values

examples/default/README.md, examples/singleregion/README.md, examples/singleregion/main.tf, examples/singleregion/versions.tf, scripts/ci_tests.sh
Heads up that this documentation update is intended to happen after we release 0.3.2 (which happened already, yay!)
This updates the examples to add a `>=` requirement for the module to make sure the recent changes are included.
Testing a local deploy using this branch `ref=`.
=> docs(examples): Update examples for 0.3.2 usage

main.tf
This PR fixes the bucket policy to allow PUT, GET on bucket objects. Previously the resource was set to the bucket ARN.
Set the source of the module to the GitHub ref:
```
git::https://github.com/lacework/terraform-aws-agentless-scanning?ref=fix-bucket-policy
```
=> fix: Update bucket policy to correct object ARN

main.tf
This PR adjusts the Security Group configuration within the regional scan resources to work around [this issue](https://github.com/hashicorp/terraform-provider-aws/issues/26666).
This also changes the configuration to use the default security group within the VPC, rather than creating a new one.  This matches the behavior we use in CloudFormation deployments: https://github.com/lacework-dev/sidekick/blob/main/cloudformation/scan-regional.json#L104-L118
Tested changes in my AWS account and verified that configuration matches CloudFormation deployment.
N/A
=> fix: changed security group configuration to match CloudFormation

README.md, main.tf, output.tf, variables.tf
Really nit-picky code formatting changes for consistency (`terraform fmt` and spacing) - and also updated README.md with a `terraform-docs markdown . --hide-empty` similar to our other modules.
With my 👀 
N/A
=> chore: formatting consistency and terraform-docs output

README.md, examples/singleregion/main.tf, main.tf, variables.tf
This is a quality of life change that allows the caller to set the VPC CIDR range.
This can be helpful if VPC peering is ever used or for organization / simplicity purposes if the existing static range overlaps other ranges.
Deploy the module locally with a new VPC range, validate the changes apply and that as scan completes.
=> feat: Allow VPC CIDR to be set

versions.tf
Updates the Lacework provider version requirement, because the `lacework_integration_aws_org_agentless_scanning` resource used in 0.5.0 of the module was added in version 0.27 of the provider.
I'm being a little lazy and editing in the browser, was going to wait and see if it passes your CI. :) Happy to test something else locally if need be.
=> fix: Update Lacework provider requirement to 0.27

examples/multi-account-multi-region/versions.tf, examples/single-account-multi-region/versions.tf, examples/single-account-single-region/versions.tf, versions.tf
set version of terraform-provider-lacework to 1.0.0
[_Created by Sourcegraph batch change `darren.murray/terraform-provider-updater`._](https://lacework.sourcegraph.com/users/darren.murray/batch-changes/terraform-provider-updater)
=> chore: update Lacework provider version to v1

README.md, main.tf
This adds a public access block and AWS-managed server side encryption settings to the S3 bucket.
Apply the settings to an existing bucket and validate end to end.
N/A
=> feat: Add default encryption and public access block to S3

main.tf, variables.tf
Customer requires that IAM roles and policies are created out of band (manually) from Terraform code. They can then be supplied back to the TF code to complete the deployment process.
These code changes make it possible to create the policies and roles ahead of time, and them supply the ARNs to the Terraform code at deployment time. Some assumptions can be made about resource ARNs based on the AWS account being deployed into and the Suffix input.
I deployed using the following steps
1. Created IAM policies manually
2. Created IAM roles manually
3. Supplied IAM roles to the TF code with other inputs
The process was documented in this custom deployment guide for the customer: https://docs.google.com/document/d/1WVdDbIjZocPWIwqGNpfv1AoEGZGn86Yd6uLa4fGDJes/edit#heading=h.rype6bwvii3n
`module …
=> feat: add support for using existing IAM roles and policies

README.md, examples/multi-account-multi-region/README.md, examples/single-account-existing-vpc/README.md, examples/single-account-existing-vpc/main.tf, examples/single-account-existing-vpc/versions.tf, examples/single-account-multi-region/README.md, examples/single-account-single-region/README.md, main.tf, scripts/ci_tests.sh, variables.tf
This PR is meant to allow users to provide an existing VPC in which to deploy scanner resources.  The existing VPC *must* already have an Internet Gateway attached - I didn't want to automatically create/attach one to prevent any unintended resource exposure.
Tested in a single-account lab environment.
N/A
=> feat: allow use of an existing VPC for deploying regional scan resources

main.tf
AWS is enabling SSE (server side encryption) for data at rest starting this month: https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingServerSideEncryption.html
This means we can enhance our bucket policies by forcing SSE to be used at the bucket and object level. This changes so that all of our PutObject requests are required to use SSE. This has been tested on a bucket with SSE enabled and without, in both cases the object results in SSE.
Use the new PR ref on a local module and run the scanner end to end.
RAIN-46878
=> fix: Add AWS recommended statements to enforce bucket SSE

examples/multi-account-multi-region-auto-snapshot/README.md, examples/multi-account-multi-region-auto-snapshot/management_account.tf, examples/multi-account-multi-region-auto-snapshot/scanning_account.tf, examples/multi-account-multi-region-auto-snapshot/versions.tf, scripts/ci_tests.sh
One of the main challenges when deploying agentless workload scanning through Terraform is that new AWS accounts added to an AWS Organization aren't automatically instrumented.  At this point, automatic snapshot role deployment for new accounts cannot be achieved through Terraform alone.  This PR aims to show an example of how this can be accomplished by deploying a single StackSet to the AWS Organization's management account - allowing for automatic instrumentation for new accounts.
Example documentation includes CI testing.
N/A
=> docs: added an example for automatic snapshot role deployment

examples/multi-account-multi-region-auto-snapshot/management_account.tf
This PR aims to fix an update loop (Terraform thinks an update is needed when it's not) caused by a current issue with the AWS provider: https://github.com/hashicorp/terraform-provider-aws/issues/23464
Verified that the change remediates the update loop.
N/A
=> doc: adding workaround for update loop

main.tf
This PR aims to do two things:
- When we create a VPC, we will remove the standard ingress/egress rules for the `default` security group. (CIS 5.3 for AWS recommends this)
- As a result of the above, we will **always** use a second security group customized for AWLS network traffic.
Deployed to my environment and validated rules.
https://lacework.atlassian.net/browse/RAIN-43602
=> feat: remove use the default security group

main.tf
Currently we allow permissions to ListSecrets for all resources. We want to box that in a little bit more to only ListSecrets that have the sidekick tag applied. Confirmed that the correct condition was added to the permissions as well.
More info in this thread: https://lacework.slack.com/archives/C03H3863SQG/p1675184838895419?thread_ts=1675113900.980539&cid=C03H3863SQG
I testing this by deploying an integration using this change locally and running the scanner. All succeeded with no errors.
https://lacework.atlassian.net/browse/RAIN-48300
=> Fix: Add condition to only list secrets with LWTAG_SIDEKICK resource tag

main.tf
This is related to [PR #54](https://github.com/lacework/terraform-aws-agentless-scanning/pull/54). We discovered that we no longer use ListSecrets in sidekick and therefore can delete these obsolete permissions. 
Tested via launching a new integration with the changes and running the scanner. Everything worked as expected.
=> fix: Remove AllowListSecrets Permissions from scan task policy 

README.md, main.tf
This fixes a bug detected by CI where the ECS cluster is referenced in locals where the resource may not be present:
```
Error: Invalid index
on ../../main.tf line 32, in locals:
32:       value = aws_ecs_cluster.agentless_scan_ecs_cluster[0].arn
aws_ecs_cluster.agentless_scan_ecs_cluster is empty tuple
The given key does not identify an element in this collection value.
```
Run CI tests again.
N/A
=> fix: Set ECS_CLUSTER_ARN within task_definition resource

main.tf
This fixes a bug introduced in [!52](https://github.com/lacework/terraform-aws-agentless-scanning/pull/52) to enforce that all traffic from our scanning cluster passes through our custom security group instead of the default one. For this to work, the custom security group needs to be passed as input to the scan task. 
We've made a change in the scanner to receive this security group via environment variable; this PR introduces a matching change to ensure this environment variable is set when deploying with Terraform.
Deployed a Terraform org integration in-house to reproduce the issue, and then re-deployed with this fix in place and verified that the scanning task now succeeds.
N/A
=> fix: Ensure security group is passed to scan task via environment variable

main.tf
This adds restrictions to how the Lacework agentless scanner uses KMS keys. The scanner always runs in a user's cloud and does not provide any access outside of the organization to KMS keys. However, the scanner does not access KMS directly, but rather needs KMS access on behalf of EC2 and EBS. These keys are used indirectly when GetSnapshotBlock APIs are used on snapshots with encrypted blocks.
Several scenarios were tested where:
- The default AWS KMS key was used to encrypt a volume.
- A customer-managed key was used to encrypt a volume.
- The scanner was installed in a dedicated scanning account and monitoring other accounts in the organization.
N/A, this is a proactive hardening fixup.
=> fix: Add kms:ViaService condition to KMS policy statements

main.tf, variables.tf
In one of our customers setup we are not using IGWs. The usage is prohibited. The internet facing traffic is completely routed via transit gateway and direct connect to an on-prem firewall/proxy setup. Which means that we cannot deploy the regional setup. That's why I added a new optional variable `use_internet_gateway` having its default value set to `true`. This variable should indicate whether to use an IGW for internet facing traffic or not.
We got the following error:
> │ Error: no matching EC2 Internet Gateway found
│
│   with module.lacework_aws_agentless_scanning_regional.data.aws_internet_gateway.selected[0],
I then used my local fork presented in this PR instead of the release version of the module.
First I changed nothing so that the default of `use_internet_gateway` which is …
=> feat: Allow usage of internet gateway to be optional

README.md, main.tf
To enable bucket ACL the ObjectOwnership parameter must be set to ObjectWriter.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
ran terraform plan
https://lacework.atlassian.net/browse/GROW-1534
=> fix: s3 bucket ownership controls

examples/multi-account-lw-org/README.md, examples/multi-account-lw-org/management_account.tf, examples/multi-account-lw-org/monitored_account.tf, examples/multi-account-lw-org/scanning_account.tf, examples/multi-account-lw-org/versions.tf, main.tf, variables.tf
This is the last change needed to enact LW Org Support for Agentless (for AWS). It adds an account mapping variable and sets it within the "lacework_integration_aws_org_agentless_scanning" resource. 
Tested the following scenarios:
1) As an Org Admin, tested by deploying with an account mapping and `organization = true` parameter set in lacework provider options. **Outcome:** The deployment went through successfully, creating all resources & beginning a scan. The integration showed in the LW Org Account and the account mapping file was created / transformed from Terraform successfully.
2) As an Org Admin, tested without an account mapping, expecting an error for the outcome and the integration to NOT be created successfully. When deploying an org integration from the LW Org Account, an …
=> Add account mapping variables for org integrations

versions.tf
The PR https://github.com/lacework/terraform-provider-lacework/pull/473 introduced a new field named `org_account_mappings` which is only available from version `1.8.0` and above.
We made use of this new variable with PR https://github.com/lacework/terraform-aws-agentless-scanning/pull/81 but we forgot to bump the min version, this causes potential issues like https://github.com/lacework/terraform-aws-agentless-scanning/issues/83 where users might be using an older version of the Lacework provider that does not have this new field.
The fix is to update the version constraint to `~> 1.8`
Note: If you don't know about the pessimistic constraint, please read this doc; https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-syntax
Ran terraform …
=> fix: bump lacework provider min version to '~> 1.8'

main.tf
This fixes https://lacework.atlassian.net/browse/RAIN-64969. The security group ingress rule created as part of agentless integrations was triggering Lacework policies in customer environments.
The rule itself is not insecure -- it only allows traffic from within the security group, not the wider internet -- there is no longer any reason to have an ingress rule in the first place. This PR removes it entirely. 
I made this change in a local version of our Terraform provider and created a new agentless integration with it, confirming that scans still run and succeed as expected. See results here: https://ui.honeycomb.io/lacework/datasets/agentless-sidekick-prod/result/vfV3do9kiJP/trace/j1KAiWymLrX
https://lacework.atlassian.net/browse/RAIN-64969
=> fix: remove ingress rule allowing traffic within security group for agentless integrations

main.tf, variables.tf
This is part of the work of multi-volume (secondary volume) and stopped instances scanning features for agentless workload scanning. We are finishing up the feature by adding a toggle / boolean for integrations to indicate if they want to turn on Multi-Volume scanning and/or Stopped Instances scanning. This is handled on the backend (in sidekick) to "turn on" the feature if the boolean is set to true.
Last part of: https://github.com/lacework/go-sdk/pull/1275, https://github.com/lacework/terraform-provider-lacework/pull/484
I tested this by running terraform against this commit and added the scan_multi_volume and scan_stopped_instances (set to true and false respectively). Terraform was successfully deployed and shows correct booleans in the UI. …
=> feat (RAIN-54831) Add scan multi volume & scan stopped instances field options

main.tf, variables.tf
This is part of the work of multi-volume (secondary volume) and stopped instances scanning features for agentless workload scanning. We are finishing up the feature by adding a toggle / boolean for integrations to indicate if they want to turn on Multi-Volume scanning and/or Stopped Instances scanning. This is handled on the backend (in sidekick) to "turn on" the feature if the boolean is set to true.
Last part of: https://github.com/lacework/go-sdk/pull/1275, https://github.com/lacework/terraform-provider-lacework/pull/484
I tested this by running terraform against this commit and added the scan_multi_volume and scan_stopped_instances (set to true and false respectively). Terraform was successfully deployed and shows correct booleans in the UI.
Issue …
=> feat(RAIN-54831): Add multi volume & scan stopped instances variable fields

main.tf
This fixes https://lacework.atlassian.net/browse/LINK-1998. This changes our terraform to follow best practices and further scope down the permission KmsGrant to only allow use on AWS resources.
Issue
https://lacework.atlassian.net/browse/LINK-1998
How did you test this change?
I made this change in a local version of our Terraform provider and created a new agentless integration with it, confirming that scans still run and succeed as expected. https://ui.honeycomb.io/lacework/datasets/agentless-sidekick-prod/result/vxN2xQHKX6j
https://lacework.atlassian.net/browse/LINK-1998
=> fix: add condition to kms to only operate on aws resources

main.tf
This fixes https://lacework.atlassian.net/browse/LINK-2014. This changes our terraform to scope down the ingress and egress rules allowed by the subnet NACL.
I made this change in a local version of our Terraform provider and created a new agentless integration with it, confirming that scans still run and succeed as expected.
https://lacework.atlassian.net/browse/LINK-2014
=> fix: Update default nacl

README.md, main.tf, variables.tf
Fixes https://github.com/lacework/terraform-aws-agentless-scanning/issues/104 by adding a new optional variable `bucket_tags`.
Also inadvertently fixes some terraform formatting.
Backwards compatibility: I tested my version of the module with my existing configuration, and saw no changes or errors in the bucket resource.
Feature validity: I then added an input to my configuration and the plan showed a new tag would be added to the bucket resource.
https://github.com/lacework/terraform-aws-agentless-scanning/issues/104
=> feat: users should be able to tag bucket (#104)

main.tf
The `kms:GrantIsForAWSResource` condition key only applies to `CreateGrant`, `RevokeGrant`, and `ListGrants`: https://docs.aws.amazon.com/kms/latest/developerguide/conditions-kms.html#conditions-kms-grant-is-for-aws-resource
Having it apply to other APIs will cause them to fail.
Deploy with `source = <commit_id>` using the module/documentation. And test with:
- Customer-managed KMS key
- AWS-managed KMS key
N/A
=> fix: Limit kms:GrantIsForAWSResource condition key to kms:CreateGrant

main.tf
If a user is chaining modules to create a single IAM role and passing the external id from the IAM Role module, Terraform will error with:
```
The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created.
```
Example Gist of how to chain ALL our AWS modules to deploy Lacework.
https://gist.github.com/afiune/08a4ef4547dab13ce2c1367a122543a6
Used the Gist to deploy all integrations into a single AWS account
https://lacework.atlassian.net/browse/GROW-2468
=> fix: `count` from lacework_external_id resource

README.md, versions.tf
The PR https://github.com/lacework/terraform-aws-agentless-scanning/pull/97 used a new resource `lacework_external_id ` which is only available from version `1.15.0` and above but we forgot to bump the min version, this causes issues like https://github.com/lacework/terraform-aws-agentless-scanning/issues/107 where users might be using an older version of the Lacework provider that does not have this new resource.
The fix is to update the version constraint to `~> 1.15`
Note: If you don't know about the pessimistic constraint, please read this doc:
https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-syntax
Closes https://github.com/lacework/terraform-aws-agentless-scanning/issues/107
=> fix: bump lacework provider min version to '~> 1.15'

main.tf
This fixes https://lacework.atlassian.net/browse/LINK-2014. This changes our terraform to scope down the ingress and egress rules allowed by the subnet NACL.
I made this change in a local version of our Terraform provider and created a new agentless integration with it, confirming that scans still run and succeed as expected.
https://lacework.atlassian.net/browse/LINK-2014
=> fix: Skip port 3389

main.tf
This fixes https://lacework.atlassian.net/browse/RAIN-75027. This changes our terraform to follow best practices and further scope down the permission KmsGrant to only allow use on AWS resources.
Issue
https://lacework.atlassian.net/browse/RAIN-75027
How did you test this change?
I made this change in a local version of our Terraform provider and created a new agentless integration with it, confirming that scans still run and succeed as expected. 
https://lacework.atlassian.net/browse/RAIN-75027
=> fix: Scope down create tag permissions

main.tf
(note this is a redo of https://github.com/lacework/terraform-aws-agentless-scanning/pull/118 because I couldn't seem to sign the previous PR)
Pass in the key secret manager KMS key ARN id to be used for cloudwatch log group encryption.
Testing on Agentless tier
* Created a KMS
* Modified https://github.com/lacework/terraform-aws-agentless-scanning/tree/main/examples/single-account-single-region to create a testing deployment
* Edited the KMS access policy so it could be used for the newly created log group
* Re-ran the above deployment with my change, observe that KMS has been enabled :
https://lacework.atlassian.net/browse/LINK-2235
=> [repeat #118]Pass in KMS key for Cloud Watch

main.tf
Tighten up the perm of `iam:PassRole` slightly. `iam:PassedToService` allows one to restrict what services the role is passed to. In our case, it's ECS.
There's potential to use `resources` to tighten up things a bit further. Checking the "Access Advisor" of the IAM role, I noticed that the role uses 
* STS
* Secret Manager
* KMS
* EC2
* ECS
* S3
and decided not to replace the `["*"]` constraint we currently because I think making it more restrictive there may not help too much and runs the risk of breaking stuff. 
deploy to AWS and test out.
https://lacework.atlassian.net/browse/RAIN-91410
=> fix: tighten up the passrole permission a bit

main.tf
This aligns the task policy to the policy we have in CloudFormation. It fixes a bug where `sts:AssumeRole`
We are testing from this branch.
N/A
=> fix: Align task policy to CloudFormation and add AssumeScanRoles

main.tf
This updates the task definition in Terraform to match CloudFormation.
This sets optional fields to be empty values and sets the default CPU = 4 (4096 in [Fargate units](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu)) and Memory = 8GB.
```
terraform init # Use source = to this PR's ref
terraform plan
terraform apply
```
Then re-plan and assure no changes
```
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
N/A
=> fix: Add unused optional ECS task parameters

README.md, main.tf
This adds flow logs for traffic type = REJECT to adopt best practice recommendations. These logs are only added to VPCs that are created/managed by this module. If an existing VPC is used, then it is up to the code managing that VPC to set flow log configuration.
Integration tests.
https://github.com/lacework/terraform-aws-agentless-scanning/issues/86
=> feat: Add VPC flow logs for module-created VPCs

main.tf
This updates the VPC flow logs to point to the S3 bucket managed by agentless. This will apply the correct age-out policy for the logs.
Create an instance of this module using Terraform and validate the flow log resource is created.
N/A
=> feat: Use S3 bucket for flow logs destination

README.md, main.tf, variables.tf
https://lacework.atlassian.net/browse/GROW-3001
aws_flow_log was not created successful with multiple regions selected. 
Add variable to disable the creation of aws_flow_log 
Tested `terraform apply` locally
=> fix: Add variable to disable aws_vpc_flow

examples/multi-account-lw-org/README.md, examples/multi-account-multi-region-auto-snapshot/README.md, examples/multi-account-multi-region/README.md, examples/single-account-existing-vpc-networking/README.md, examples/single-account-multi-region/README.md, examples/single-account-single-region/README.md, examples/use-existing-iam-roles-multi-region/README.md, examples/use-existing-iam-roles-single-region/README.md
We are in the process of updating our public facing FortiCNAPP documentation to reference our Terraform examples directly (i.e. by linking to https://registry.terraform.io/modules/lacework/agentless-scanning/aws/latest) rather than replicating the Terraform in-line on the docs page.
The AWS examples in this repo are already and good shape and only one small change is needed for this transition: we need to add a sample `version.tf` to each example. That's all that this PR accomplishes.
N/A. Docs only change.
https://lacework.atlassian.net/browse/AWLS2-550
=> chore(AWLS2-550): update Terraform examples
